### ISSUE TITLE
Standalone Profile Page

### ISSUE THREAD

**Issue by renodubois** [siggame/ophelia#105]
Since we'll likely have a list of users, we should have a profile for each user. 

Should include support for the following to be passed as props:
- profile picture
- username
- bio
- team they're on?

If anything else might be a good fit for that page, go ahead and drop it here.

**Comment by cmparsons** [comment]
Should I worry about how that data will be fetched right now? If not, should I just pass in dummy data into the component for now?

**Comment by cmparsons** [comment]
Also, should I just replace what is already in the Profile component currently?

**Comment by renodubois** [comment]
So this will be taking advantage of our component/container design here - since this is a component (visual, only accepts props) you can just assume the data being passed is correct, and just focus on displaying it. 

I'd go ahead and replace what's in `components/Profile` currently, and use `container/ProfileContainer` to send it dummy data via props. Actually making the `ProfileContainer` do real requests will be a separate issue, this is more focused on the visual aspect of the Profile component.

Does that make sense & answer your questions?

**Comment by cmparsons** [comment]
So this issue is just related to having a component that will only show any profile information passed into it, and not a form-like component where users can edit their profile information?

**Comment by renodubois** [comment]
Yep, that's correct! Editing this information will be another issue.

**Comment by renodubois** [comment]
Fixed by #161
