### ISSUE TITLE
GAME STATS

### ISSUE THREAD

**Issue by jonsimington** [siggame/ophelia#11]
People want this so bad.

We were talking about making this its own service that sits between the arena and the website

Ability to view arena stats from the games page

**Comment by russleyshaw** [comment]
Wouldnt it be better to just make this a requirement on the arena and allow the webserver to request the information?

**Comment by jonsimington** [comment]
yep, the arena should calculate it, or a separate middleware

**Comment by JacobFischer** [comment]
I think it should be middleware. Basically a program that sits between the website and arena, as it's basically 50% each.

Plus if it falls out of use we don't want broken stats bringing down the entire website/arena.

This would be a great project to give to a few members as let them run with it.

**Comment by Daniel17sep** [comment]
It's a lot easier to calculate game stats as game state changes happen, so whatever component calculates this should be receiving state updates as they happen.
