### ISSUE TITLE
Filter Component

### ISSUE THREAD

**Issue by michael-beaver** [siggame/ophelia#126]
It would be awesome to add a component that would let you filter the games based on various parameters.

This could do some pretty extra queries, such as filtering on
 * wins/losses
 * opponent name
 * version number
 * submission tag (for the future when that is implemented)

The back end would need to be changed to match this, but a lot of the work would be on the front

**Comment by renodubois** [comment]
I think is fixed by #166, minus submission tags. Going to close this for now.
