### ISSUE TITLE
Consider Migrating Project to yarn

### ISSUE THREAD

**Issue by renodubois** [siggame/ophelia#135]
https://yarnpkg.com/en/

Yarn seems to be faster than NPM in most cases, and would likely be a pretty painless switch.

How do we feel about this? Worth it or no?

**Comment by michael-beaver** [comment]
npm seems perfectly fine on linux, but using it on windows takes absolutely forever. Yarn doesn't have those same problems does it? 

Also would there be other changes other than it speeding things up? Or is it meant to just be faster?

**Comment by cmparsons** [comment]
There's really no difference in yarn and npm besides speed performance. I've used both yarn and npm in projects and haven't had any issues. 

My only concern is is that I don't know if it's supported on windows.

**Comment by renodubois** [comment]
#158 fixes this, closing.
