### ISSUE TITLE
Issue with site not checking if submitted password is invalid

### ISSUE THREAD

**Issue by michael-beaver** [siggame/ophelia#136]
We recently had a report of someone who was having trouble making an account, and after working with them for a bit we discovered that the password they were using was not valid, but the front end wasn't telling them that.

Essentially we just need to double check that the front end and back end are using the same checks

**Comment by renodubois** [comment]
Is this not fixed with #134? Want to make sure before trying to assign this.

**Comment by michael-beaver** [comment]
I haven't seen this crop up again and haven't been able to identify it any more. I think I am just going to close this for now and hopefully #134 Did enough to remedy any further user experience issues
