### ISSUE TITLE
Infinite Loading Overlay when no games present

### ISSUE THREAD

**Issue by renodubois** [siggame/ophelia#139]
When you log onto an account with no games attached to it, instead of just showing that there are no games, there is a 401 error and the loading overlay just keeps going.

This is likely a frontend component not properly handling the "no games" case, but I'm not certain on that.

**Comment by user404d** [comment]
Bump, I've seen this too, except it happens when first logging in **even with games played**. I have to reload to see my games get loaded properly.

Chrome, macOS.

**Comment by user404d** [comment]
My guess is that my problem is related to the JWT expiring and not getting refreshed. I'm not sure if my problem is really related to your problem aside from the games not loading (ie the overlay keeps spinning) because neither games nor build submissions display.

**Comment by renodubois** [comment]
This _should_ be fixed by #138. Closing for now.

Will reopen if it rears its head again.
