### ISSUE TITLE
Overlapping divs block pagination navigation

### ISSUE THREAD

**Issue by user404d** [siggame/ophelia#141]
<img width="838" alt="screen shot 2018-03-10 at 04 23 41" src="https://user-images.githubusercontent.com/6620882/37241212-0e207d76-241b-11e8-975f-101be9dcc580.png">

Unable to choose page of results or navigate them with smaller window size.

**Comment by michael-beaver** [comment]
Thanks for posting this, but it looks like it is a duplicate of #125 , and hopefully it will be fixed with #133 , we plan on moving through the PRs soon

**Comment by user404d** [comment]
oh shoot yeah you're right, my bad
