### ISSUE TITLE
Client output is for the wrong team

### ISSUE THREAD

**Issue by user404d** [siggame/ophelia#146]
I think this is the culprit? 

https://github.com/siggame/ophelia/blob/bb43367d078c3d1b1e333e630085489dd8aa6f36/server/db/games.js#L77

Basically you're saying you want the opponent's rows and not the team you're interested in by using that query. I could be wrong as I haven't done a deep dive, but this could definitely be the problem. The reason this hasn't shown up before is that they both share the same game log entry for a match so it wouldn't have popped up until now.

**Comment by michael-beaver** [comment]
Good catch, I know exactly what is causing that. That piece of code is for finding the opponents team name, but that portion is being overhauled anyways, I'll go ahead and make a quick fix for this in the mean time though

**Comment by michael-beaver** [comment]
This should be fixed by #147
