### ISSUE TITLE
Lock down dependencies

### ISSUE THREAD

**Issue by DaWeish** [siggame/ophelia#15]
We should probably use npm shrinkwrap to specify the transitive dependencies of our modules to prevent stuff from breaking in the future *cough cough*

**Comment by jonsimington** [comment]
put the versions in `package.json` so `npm install` will auto download the right versions

**Comment by DaWeish** [comment]
The problem comes when a dependency in package.json has another dependency which we don't specify a version for which could be cause changes if it is updated

**Comment by DaWeish** [comment]
They sorta specify why shrinkwrapping would be useful in some cases on the npm module page - [shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap)

**Comment by russleyshaw** [comment]
Node JS and its packages move really fast, but one fear that I have is if they are locked down for too long, it is a much larger development effort to update to the newer packages. I almost feel like it would be easier to address any breaking issues as they arise, rather than alll at once when you guys decide to update dependencies.

**Comment by DaWeish** [comment]
I think it would be ideal that if a committed release version of code works when it is pushed, a month later, someone should be able to pull that code down, and install the same dependencies to get the same behavior without going on a wild goose chase to see which version of what transitive dependency changed. This would be a relatively easy thing to do and all I meant by this was basically to keep a shrinkwrap file in the repo specifying the dependency versions that were being used when the code was commited for repeatability sake. I was not implying that we lock into the current version of all of our dependencies. Merely that once code is commited, especially to master, the tested versions of all dependencies should be easily recoverable.
