### ISSUE TITLE
Chess Visualizer Counting Down Wrong Timer

### ISSUE THREAD

**Issue by mediumreddog** [siggame/ophelia#201]
<img width="1509" alt="screen shot 2019-03-05 at 5 38 47 pm" src="https://user-images.githubusercontent.com/2218132/53845125-9d075780-3f6d-11e9-8e97-cfa8258a7478.png">

It is white's turn, but the black player's timer is counting down.

**Comment by JacobFischer** [comment]
Ah this is actually a visualizer bug. The Vis repo is here: https://github.com/siggame/Viseur

I'm the one responsible for that bug 😅
