### ISSUE TITLE
Spectator Taking Player Slot in Visualizer

### ISSUE THREAD

**Issue by mediumreddog** [siggame/ophelia#202]
To reproduce:

1. Connect to a lobby as spectator on http://vis.siggame.io/
2. Connect an AI to the lobby as a player.
3. The game starts with the spectator as the other player.

**Comment by JacobFischer** [comment]
Ah this is actually a visualizer bug. The Vis repo is here: https://github.com/siggame/Viseur

I'm the one responsible for that bug 😅
