### ISSUE TITLE
MISC - Rewrite the README w/ updated instructions for Vagrant/Docker

### ISSUE THREAD

**Issue by renodubois** [siggame/ophelia#37]
I'll do this once both of those setups are done, just wanted to remind myself here

**Comment by russleyshaw** [comment]
I'd keep the description short.

It might be best to create a basic Docker tutorial and Vagrant tutorial as the SIG-Game user under our new Medium.com blog that way we can just link to it.

**Comment by renodubois** [comment]
My plan was just to have the base commands to get everything set up, leaving any further explanation to something like a Medium post. 

It would be something along the lines of: "install vagrant + virtualbox, run this command, go here to see the website"

**Comment by russleyshaw** [comment]
I'd do the opposite. 

Installing Vagrant & VirtualBox are common things you'd need to do and not specific to the project. I'd put all general things in the post and any project specific things in the readme.

**Comment by renodubois** [comment]
I want a user to be able to clone this repo, check out the readme and have all the information they need to see the Ophelia home page. 

Having them click + read an article seems counterproductive to that strategy. 

I understand it's a common tool, but I want this to be as easy as possible, without them having to bumble around a bunch of different websites.

**Comment by russleyshaw** [comment]
W/E, I was just thinking it was a common thing we could use between other SIG-Game components, Arena included. Its annoying to have to update 10 different places rather than just one when either our devops strategy changes or when something about the tools themselves changes.

**Comment by russleyshaw** [comment]
Nothing about Docker or vagrant is specific to Ophelia and it should be treated as such

**Comment by renodubois** [comment]
I guess my perspective here is that the blog posts should do a good job of explaining why & how we use Docker/Vagrant (which I think your Docker one covers well, by the way) but I just want this README to be "this is how to get it working on your computer", in which I will link your article and the Vagrant one for a more in-depth explanation on why we're using these tools.
