### ISSUE TITLE
Arena Sync

### ISSUE THREAD

**Issue by jonsimington** [siggame/ophelia#4]
Every time period, check the arena api for games which have not been pulled in, and load these new games into the database.

We have a python script to do this currently, should be easy to translate to JS, or even use it in the new project

**Comment by renodubois** [comment]
The current script can be found here: https://github.com/siggame/webserver/blob/develop/webserver/hermes/tasks/arena_sync.py

**Comment by brianwgoldman** [comment]
Any chance we can move this to arena pushing logs as they are created instead of the web server polling periodically? It will make for a much better user experience and likely reduce the load on both sides.

**Comment by DaWeish** [comment]
This isn't something that the web site should be doing regardless of a push/pull architecture. I think ideally it should be a separate service which polls the arena and pulls the new game logs.

**Comment by jonsimington** [comment]
@Daniel17sep are you willing to send us logs at some api endpoint when the games finish?

**Comment by Daniel17sep** [comment]
Would that just consist of posting a json or something?
