### ISSUE TITLE
User Model

### ISSUE THREAD

**Issue by jonsimington** [siggame/ophelia#7]
First, Last, email, username, password, about me. Also allow for managing user activity, permissions, and group memberships, also eligibility.

**Comment by renodubois** [comment]
When new users get added to the MegaMinerAI database, use the GitLab API to create them a GitLab account in that same instance. This way they don't have to worry about 2 separate accounts for one competition

**Comment by renodubois** [comment]
So after looking at how we will interact with the arena and GitLab, we're going to go ahead and still handle some user stuff on our end, but with a database field that links to a GitLab user ID.

I'm thinking that when a user goes to register for a tournament, we can make them be connected to GitLab first, so that we can force their integration before they are allowed to compete.

**Comment by renodubois** [comment]
So that's a fair concern. I think we can use the GitLab API to make changes on both fronts at the same time if we would want that, but I wasn't sure if that's what we were going for.

**Comment by russleyshaw** [comment]
(accidental close)

**Comment by russleyshaw** [comment]
I was just thinking of the possibility of letting gitlab manage the concept of users and teams(projects) and storing extra info on the database

**Comment by renodubois** [comment]
That sounds good to me. Would we have to facilitate some sort of OAuth then between megaminerai.com and git.megaminerai.com or wherever gitlab is stored?

**Comment by jonsimington** [comment]
yes

https://docs.gitlab.com/ee/integration/oauth_provider.html

**Comment by renodubois** [comment]
So the users need to create an account on GitLab, then use OAuth2 to authenticate w/ MegaMinerAI.com, if I'm understanding all of this correctly.

**Comment by jonsimington** [comment]
Yea, they would create their account on gitlab, then we configure ophelia to use gitlab as the oauth source described in the link I posted.  From there on, gitlab would be our source of truth for user accounts

**Comment by renodubois** [comment]
Ok, I'm going to try and see if I can't get a simple OAuth config spun up.

**Comment by renodubois** [comment]
Migrated to #21.
