### ISSUE TITLE
Games Component supporting Pagination

### ISSUE THREAD

**Issue by renodubois** [siggame/ophelia#77]
When the backend supports pagination, the frontend will need to be able to support it.

When we request info about games from the backend, we'll get a number of pages of games. So we need to have the games component have page navigation based on the number of pages, and clicking on the next page will query the backend for that info. (i.e. "Hey, get me page 3 of this user's game data").

Basic Potential Mockup:
![Basic Mockup of Page Navigation](http://i.imgur.com/P4g1TJI.png)

Some things to think about:
- What if there are say, 15 pages? We should have a max on how many page numbers get displayed at one time (maybe 5 or so) and we should change the page numbers around the currently selected one.
    - For example, if a user is on page 12, you can imagine that being surrounded by page 10, 11, 13, 14; not 1, 2, 3, 4 - etc.
- In the mockup I have the selected number in the center - is this functionality we can do? Is there going to be confusing logic for that?

To Start:
- Go ahead and design a sub-component called `PaginationNav` or something similar, and just make it display a number of pages, and work on getting the problems I talked about above (i.e. having a lot of pages and how to handle that) before even getting started on making it change game pages.
- Once you have a component that can handle any number of pages well, go ahead and add some way for the component to communicate with the backend. Since this might be something that's useful in other places, consider making a prop for the URL it needs to communicate, so we can potentially reuse it.

**Other things to consider:**
- There might be a component similar to this (that someone else has made) that already works really well, and that wouldn't be a bad thing. Maybe do a bit of research into that before starting. It's not a definite one way or another, but it's something to consider.

**Comment by michael-beaver** [comment]
Currently how we are thinking about doing this is the back end will respond with a certain large number of games (currently set at 100) and the front end will break this up into pages of 10 or so, and then once it reaches the end of it's current set it will request the next page from the back end.

This can be accomplished in a couple of different ways, I am thinking that making the games array in the game store work as a 2 dimensional array would be appropriate.

**Comment by renodubois** [comment]
This has been implemented and is live currently.
