### ISSUE TITLE
Git Interaction

### ISSUE THREAD

**Issue by jonsimington** [siggame/ophelia#8]
allowing members of the team to push/pull using a team wide password. 

- Git server is written in python, I think our goal here is to:
    - find a JS git client
    - create (or copy from old proj.) front end templates

**Comment by jonsimington** [comment]
Let teams choose which commit to submit to the arena

**Comment by jonsimington** [comment]
Ability to change the repo's password from front end

**Comment by renodubois** [comment]
Looking like this will be interaction with GitLab now. Need to make it so we can create accounts for teams and make repos there.

**Comment by renodubois** [comment]
Also work w/ OAuth2 to create GitLab accounts for competitors and then assign them to Groups on GitLab based on their groups on the competition website
