### ISSUE TITLE
Submissions endpoint on back end

### ISSUE THREAD

**Issue by michael-beaver** [siggame/ophelia#83]
The back end needs a submissions end point which needs to do a couple things:

- [ ] Accept file submissions from the user
- [ ] Ensure the file is of a certain type (.zip, .7z, .rar, etc.)
- [ ] Do a check to make sure is the correct size/isn't dangerous (no zip bomb, or anything else)
- [ ] Proxy the user's request to their endpoint on the arena.

**Comment by willarderic** [comment]
Library I found for express file uploads
https://www.npmjs.com/package/express-fileupload
